// GENERATED by `npx tsx scripts/art-geometry.ts`. The geometry of every painted character that the page needs before
// the character module has loaded: the part markers sit on the painting's anchors from the very first render
// (anchors.ts), so they never jump when the module or its texture arrives. The same numbers as each module's `size`,
// `pad` and `anchors` (tests/v2/art-geometry.test.ts fails while they differ).
export interface Geometry {
  size: [number, number];
  pad: [number, number];
  anchors: Record<string, [number, number, number]>;
}

export const GEOMETRY: Record<string, Geometry> = {
  'cog-rat': { size: [1216, 832], pad: [190, 100], anchors: { 'rat-jaw': [118, 216, 34], 'rat-plate': [690, 420, 130], 'rat-tail': [1060, 560, 80], core: [600, 470, 110], eyes: [310, 162, 36] } },
  'rust-mite': { size: [1216, 832], pad: [200, 110], anchors: { 'mite-pincers': [265, 480, 78], 'mite-gland': [725, 255, 150], core: [610, 410, 90], eyes: [418, 488, 38] } },
  'brass-beetle': { size: [1216, 832], pad: [200, 110], anchors: { 'beetle-mandibles': [112, 452, 70], 'beetle-shell': [740, 490, 85], 'beetle-carapace': [880, 250, 230], core: [620, 370, 90], eyes: [232, 420, 40] } },
  'oil-slick': { size: [1216, 832], pad: [300, 100], anchors: { 'slick-nozzle': [620, 150, 85], 'slick-spitter': [288, 388, 60], core: [620, 340, 90], eyes: [288, 388, 40] } },
  'spring-imp': { size: [1216, 832], pad: [220, 120], anchors: { 'imp-tail': [1045, 520, 95], 'imp-key': [680, 365, 58], core: [680, 430, 100], eyes: [310, 195, 75] } },
  'gearhound': { size: [1216, 832], pad: [250, 110], anchors: { 'hound-fangs': [125, 235, 95], 'hound-snout': [62, 162, 36], 'hound-haunch': [938, 468, 72], core: [600, 255, 90], eyes: [160, 125, 26] } },
  'tinpot-general': { size: [896, 1152], pad: [380, 130], anchors: { 'tinpot-horn': [655, 826, 70], 'tinpot-bugle': [100, 850, 70], 'tinpot-sabre': [735, 280, 90], 'tinpot-hat': [445, 200, 130], core: [445, 625, 110], eyes: [452, 413, 70] } },
  'foreman': { size: [896, 1152], pad: [300, 230], anchors: { 'foreman-wrench': [715, 770, 100], 'foreman-grate': [448, 432, 97], 'foreman-apron': [448, 690, 110], 'foreman-bulwark': [448, 655, 100], 'foreman-rivet': [175, 690, 100], core: [448, 560, 60], eyes: [443, 201, 45] } },
  'boilermaker': { size: [896, 1152], pad: [150, 60], anchors: { 'queen-crown': [445, 165, 115], 'queen-scepter': [140, 150, 100], 'queen-gauge': [448, 478, 62], 'queen-furnace': [448, 950, 75], 'queen-staff': [750, 185, 95], 'queen-ember': [448, 880, 130], 'queen-cinder': [715, 540, 75], core: [448, 590, 80], eyes: [445, 263, 40] } },
  'clockmaker': { size: [896, 1152], pad: [230, 170], anchors: { 'clock-hour': [443, 306, 100], 'clock-tick': [588, 683, 52], 'clock-minute': [711, 757, 46], 'clock-tock': [443, 598, 52], 'clock-gov': [445, 455, 75], 'clock-wheel': [446, 172, 110], 'clock-bell': [443, 530, 52], 'mem-drill': [268, 195, 48], 'mem-governor': [446, 45, 44], 'mem-valve': [446, 222, 44], 'mem-chime': [281, 706, 52], core: [443, 430, 45], eyes: [446, 142, 45] } },
  'tinker': { size: [1216, 832], pad: [70, 70], anchors: { hand: [565, 360, 38], head: [725, 150, 85], satchel: [905, 330, 95], core: [765, 375, 60], eyes: [690, 176, 40] } },
  'sprocket': { size: [1216, 832], pad: [40, 30], anchors: { nose: [103, 288, 14], eye: [193, 240, 16], collar: [608, 380, 24], tail: [1068, 75, 30], core: [600, 420, 120], eyes: [193, 240, 30] } },
};
