// GENERATED by `npm run art` (scripts/art.mjs). Do not edit: add an asset to the list in that script.
// Every `files[].path` is relative to `public/` and `bytes` is the file size on disk; `source` is the art/<asset> folder.
import type { ManifestEntry } from './types';

export const MANIFEST: ManifestEntry[] = [
  {
    id: 'cog-rat',
    act: 1,
    files: [
      { path: 'art/cog-rat/cut.webp', bytes: 75572 },
    ],
    source: 'art/cog-rat',
  },
  {
    id: 'rust-mite',
    act: 1,
    files: [
      { path: 'art/rust-mite/cut.webp', bytes: 51504 },
    ],
    source: 'art/rust-mite',
  },
  {
    id: 'brass-beetle',
    act: 1,
    files: [
      { path: 'art/brass-beetle/cut.webp', bytes: 62410 },
    ],
    source: 'art/brass-beetle',
  },
  {
    id: 'oil-slick',
    act: 1,
    files: [
      { path: 'art/oil-slick/cut.webp', bytes: 57300 },
    ],
    source: 'art/oil-slick',
  },
  {
    id: 'spring-imp',
    act: 1,
    files: [
      { path: 'art/spring-imp/cut.webp', bytes: 70692 },
    ],
    source: 'art/spring-imp',
  },
  {
    id: 'gearhound',
    act: 1,
    files: [
      { path: 'art/gearhound/cut.webp', bytes: 76624 },
    ],
    source: 'art/gearhound',
  },
  {
    id: 'tinpot-general',
    act: 1,
    files: [
      { path: 'art/tinpot-general/cut.webp', bytes: 48866 },
      { path: 'art/tinpot-general/hat.webp', bytes: 12966 },
      { path: 'art/tinpot-general/blade.webp', bytes: 8626 },
    ],
    source: 'art/tinpot-general',
  },
  {
    id: 'foreman',
    act: 1,
    files: [
      { path: 'art/foreman/cut.webp', bytes: 108144 },
      { path: 'art/foreman/cut-phase2.webp', bytes: 110266 },
    ],
    source: 'art/foreman',
  },
  {
    id: 'boilermaker',
    act: 2,
    files: [
      { path: 'art/boilermaker/cut.webp', bytes: 144434 },
    ],
    source: 'art/boilermaker',
  },
  {
    id: 'clockmaker',
    act: 3,
    files: [
      { path: 'art/clockmaker/cut.webp', bytes: 103970 },
    ],
    source: 'art/clockmaker',
  },
  {
    id: 'tinker',
    act: 0,
    files: [
      { path: 'art/tinker/cut.webp', bytes: 49362 },
    ],
    source: 'art/tinker',
  },
  {
    id: 'sprocket',
    act: 0,
    files: [
      { path: 'art/sprocket/cut.webp', bytes: 59024 },
      { path: 'art/sprocket/cut-happy.webp', bytes: 60106 },
    ],
    source: 'art/sprocket',
  },
  {
    id: 'bellfoot',
    act: 0,
    files: [
      { path: 'art/bellfoot/sky.webp', bytes: 167554 },
      { path: 'art/bellfoot/street.webp', bytes: 259476 },
      { path: 'art/bellfoot/foreground.webp', bytes: 56576 },
    ],
    source: 'art/bellfoot',
  },
];
