// v2 acceptance, docs/acceptance.md section 9: Enemy machines and targeting (rules 2.1 to 2.3). Generated by scripts/v2-acceptance-todos.mjs.
// Each todo becomes a real test in the build phase that owns it (E kinds move to e2e/).
import { describe, it } from 'vitest';

describe('v2 9. Enemy machines and targeting (rules 2.1 to 2.3)', () => {
  it.todo('EM1 [U] Given every enemy def (15 regular, 6 elite, 3 wardens); when build it; then it has a core with HP and 1 to 8 parts; every part has hp, action, cadence; every salvage id is a part def or `brass-key`; an anchor is named for each part');
  it.todo('EM2 [U] Given an enemy whose Jaw (8 HP) shows Attack 5x2; when a Strike 9 at the Jaw; then the Jaw breaks, its intent is cancelled, the enemy turn deals 0 from it; the 1 overkill is lost (core unchanged)');
  it.todo('EM3 [U] Given order [Jaw, core], Spur at B2 (Strike 3, 3 ticks), Jaw 5 HP, core 20; when run; then tick 1: Jaw 2 left; tick 2: Jaw breaks (1 lost); tick 3: core 17');
  it.todo('EM4 [U] Given empty order, two enemies; when Strike; then it hits the leftmost living enemy\'s front (core, or first keystone if sealed)');
  it.todo('EM5 [U] Given a sealed core; when try to add it to the order; Sweep 5; then refused; the Sweep hits its first unbroken keystone instead');
  it.todo('EM6 [U] Given an enemy with every acting part broken; when its turn; then it performs its core action only');
  it.todo('EM7 [U] Given any board and order; when preview, then Run; then per-target damage, breaks, deaths and cancelled intents in the preview equal the run\'s exactly; preview leaves state unchanged');
  it.todo('EM8 [E] Given the combat screen at 1280x800 and 667x375; when tap two parts and a core; then they show 1, 2, 3 badges on the painting\'s anchors; tapping again removes one; the order persists next turn with broken entries removed');
  it.todo('EM9 [E] Given a part shows an intent; when look at it; then the intent icon, number and HP pips sit on the part\'s anchor and follow it as the rig moves; the tooltip names the part and its action');
  it.todo('EM10 [U] Given Shatter 4 with order [e0.core], e0 has 3 parts; when run; then each unbroken part of e0 takes 4; the core takes 0 from Shatter');
  it.todo('EM11 [U] Given Drill 10 against Shell 6 and a standing Bulwark; when run; then the core takes 10');
});
