// v2 acceptance, docs/acceptance.md section 11: Wardens and phases (rules 4.7 to 4.9). Generated by scripts/v2-acceptance-todos.mjs.
// Each todo becomes a real test in the build phase that owns it (E kinds move to e2e/).
import { describe, it } from 'vitest';

describe('v2 11. Wardens and phases (rules 4.7 to 4.9)', () => {
  // WP2: real tests in tests/v2/b9-wardens.test.ts (B9a).
  // WP3: real tests in tests/v2/b9-wardens.test.ts (B9a).
  // WP4: real tests in tests/v2/b9-wardens.test.ts (B9a).
  // WP5: real tests in tests/v2/b9-wardens.test.ts (B9a).
  // WP6: real tests in tests/v2/b9-wardens.test.ts and e2e/v2-memory.spec.ts (B9a).
  it.todo('WP7 [E, C] Given the Queen\'s phase change on screen; when it plays; then the `phase` mood runs on her rig and the broken gauge stays shown broken');
});
