// v2 acceptance, docs/acceptance.md section 15: Achievements, rarity, difficulty (rules 5.6, 5.7; content). Generated by scripts/v2-acceptance-todos.mjs.
// Each todo becomes a real test in the build phase that owns it (E kinds move to e2e/).
import { describe, it } from 'vitest';

describe('v2 15. Achievements, rarity, difficulty (rules 5.6, 5.7; content)', () => {
  it.todo('AD1 [U] Given the catalog; when read; then about 30 achievements, each with id, condition, tier, reward; every Masterwork and Legendary part unlocked by exactly one achievement');
  it.todo('AD2 [U, E] Given an achievement\'s condition met mid-run; when the run ends; then it unlocks in the same save write as the RunRecord, shows on the trophy shelf, its reward is in the pool next run');
  it.todo('AD3 [U] Given a run; when gain parts; then never more than one Legendary in the bin; locked tiers never appear');
  it.todo('AD4 [U] Given each mode; when start a run; then enemy HP and damage, hours per act, oil heal and Brass match rules 5.7');
  it.todo('AD5 [U, E] Given no win yet / a Journeyman win; when open the clock tower door; then Overwind locked / Overwind 1 available; level N applies twists 1 to N');
  it.todo('AD6 [E, C] Given parts of each tier; when look; then each tier distinct by color and by a shape mark, not color alone');
});
