// v2 acceptance, docs/acceptance.md section 16: Art and atmosphere (D-026, docs/art-direction.md). Generated by scripts/v2-acceptance-todos.mjs.
// Each todo becomes a real test in the build phase that owns it (E kinds move to e2e/).
import { describe, it } from 'vitest';

describe('v2 16. Art and atmosphere (D-026, docs/art-direction.md)', () => {
  it.todo('AR1 [U] Given the build; when scan `src/` and `public/`; then images only under `public/art/`, WebP only, each in the art manifest with a source folder in `art/`; no audio or font files (rescoped A1)');
  it.todo('AR2 [U] Given every enemy, warden and Sprocket in the manifest; when load its rig; then idle, attack, hurt (wardens also phase; Sprocket happy, sleepy, walk) and an anchor for every part in its def');
  it.todo('AR3 [E, C] Given the title screen at both sizes; when open the game; then the painted title with animated steam and lamps; Continue, New run, Settings; the tower not covered');
  it.todo('AR4 [E] Given combat with 3 rigged enemies at 667x375 with 4x CPU throttling; when 10 s; then median and p95 frame time within the budget in docs/spike-art.md');
  it.todo('AR5 [C] Given each art gate; when the owner reviews; then one clip per asset; an art-reviewer verdict in `review/<phase>/`');
  it.todo('AR6 [C, E] Given each act and Bellfoot; when play there; then a painted backdrop with code ambience (steam, lamps) and an ambient sound bed');
});
