// v2 acceptance, docs/acceptance.md section 17: Balance v2 (rules 7.4). Generated by scripts/v2-acceptance-todos.mjs.
// Each todo becomes a real test in the build phase that owns it (E kinds move to e2e/).
import { describe, it } from 'vitest';

describe('v2 17. Balance v2 (rules 7.4)', () => {
  it.todo('BV1 [S] Given expert bot, no meta, Journeyman; when 300 runs; then win rate under 5%; greedy under 2%');
  it.todo('BV2 [S] Given 100 expert careers on the sensible path; when until first win (cap 30); then median first win between run 8 and 12');
  it.todo('BV3 [S] Given every elite and warden, bins from expert runs; when turtle and burst bots play them; then neither averages under 10% of max HP lost; the expert\'s win rate beats each by 15 points or more');
  it.todo('BV4 [S] Given the expert against each warden; when 100 fights; then median turns: Foreman 6 to 9, Queen 7 to 10, Clockmaker 8 to 12; every phase at least 2 turns in 90%');
  it.todo('BV5 [S] Given the per-part table; when offer-based impact; then highest at most 2x the median');
  it.todo('BV6 [S] Given the expert bot; when a career; then under 50 ms per turn on average');
  it.todo('BV7 [S] Given a fixed seed; when run any sim mode twice; then identical reports (v1 BS1, kept)');
});
