// `npx tsx scripts/art-geometry.ts`: rewrites src/art/geometry.ts from the character modules' size, pad and anchors.
// Run it after a rig changes (tests/v2/art-geometry.test.ts fails while the table is stale). Add an id here with its module.
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CharacterDef } from '../src/art/types';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ids = ['cog-rat', 'rust-mite', 'brass-beetle', 'oil-slick', 'spring-imp', 'gearhound', 'tinpot-general', 'foreman', 'boilermaker', 'clockmaker', 'tinker', 'sprocket'];

const lines: string[] = [];
for (const id of ids) {
  const def = ((await import(`../src/art/${id}.ts`)) as { default: CharacterDef }).default;
  const anchors = Object.entries(def.anchors)
    .map(([k, v]) => `${/^[a-z]+$/.test(k) ? k : `'${k}'`}: [${v.join(', ')}]`)
    .join(', ');
  lines.push(`  '${id}': { size: [${def.size.join(', ')}], pad: [${def.pad.join(', ')}], anchors: { ${anchors} } },`);
}

const out = `// GENERATED by \`npx tsx scripts/art-geometry.ts\`. The geometry of every painted character that the page needs before
// the character module has loaded: the part markers sit on the painting's anchors from the very first render
// (anchors.ts), so they never jump when the module or its texture arrives. The same numbers as each module's \`size\`,
// \`pad\` and \`anchors\` (tests/v2/art-geometry.test.ts fails while they differ).
export interface Geometry {
  size: [number, number];
  pad: [number, number];
  anchors: Record<string, [number, number, number]>;
}

export const GEOMETRY: Record<string, Geometry> = {
${lines.join('\n')}
};
`;
writeFileSync(join(root, 'src/art/geometry.ts'), out);
console.log(`src/art/geometry.ts: ${ids.length} characters`);
